CREATE TABLE [dbo].[Collars]
(
	[CollarId]                    INT               NOT NULL IDENTITY,
	[Name]                        NVARCHAR (50)     NOT NULL,
	[SubscriptionId]              NVARCHAR (50)     NULL,
	[VhfFrequency]                NVARCHAR (50)     NULL,
	[CollarTypeId]                INT               NULL,
	[JobNumber]                   NVARCHAR (50)     NULL,
	[Model]                       NVARCHAR (50)     NULL,
	[CollarStatusId]              INT			    NULL,
	[CollarMalfunctionId]         INT               NULL,
	[CollarRegionId]              INT               NULL,
	[CollarStateId]               INT               NULL,
	[InactiveDate]                DATETIME          NULL,
	[ProjectId]                   INT               NULL,
	[Size]                        NVARCHAR (50)     NULL,
	[BeltingColour]               NVARCHAR (50)     NULL,
	[FirmwareVersion]             NVARCHAR (MAX)    NULL,
	[Comments]                    NVARCHAR (MAX)    NULL,
	[DropOffDate]                 DATETIME          NULL,
	[EstimatedDropOff]            DATETIME          NULL,
	[EstimatedGpsFailure]         DATETIME          NULL,
	[EstimatedGpsBatteryEnd]      DATETIME          NULL,
	[EstimatedVhfFailure]		  DATETIME          NULL,
	[EstimatedVhfBatteryEnd]      DATETIME          NULL,
	[LastUpdated]				  DATETIME          NOT NULL DEFAULT GETUTCDATE(),
	CONSTRAINT [PK_Collars] PRIMARY KEY CLUSTERED ([CollarId]),
	CONSTRAINT [UK_Collars_Name] UNIQUE ([Name]),
	CONSTRAINT [FK_Collars_CollarMalfunctions] FOREIGN KEY ([CollarMalfunctionId]) REFERENCES [dbo].[CollarMalfunctions] ([CollarMalfunctionId]),
	CONSTRAINT [FK_Collars_CollarStates] FOREIGN KEY ([CollarStateId]) REFERENCES [dbo].[CollarStates] ([CollarStateId]),
	CONSTRAINT [FK_Collars_CollarStatuses] FOREIGN KEY ([CollarStatusId]) REFERENCES [dbo].[CollarStatuses] ([CollarStatusId]),
	CONSTRAINT [FK_Collars_CollarRegions] FOREIGN KEY ([CollarRegionId]) REFERENCES [dbo].[CollarRegions] ([CollarRegionId]),
	CONSTRAINT [FK_Collars_CollarTypes] FOREIGN KEY ([CollarTypeId]) REFERENCES [dbo].[CollarTypes] ([CollarTypeId]),
	CONSTRAINT [FK_Collars_Project] FOREIGN KEY ([ProjectId]) REFERENCES [dbo].[Project] ([ProjectId])
)
