CREATE TABLE [dbo].[CollaredAnimals]
(
	[CollaredAnimalId]					INT					NOT NULL IDENTITY,
	[CollarId]							NVARCHAR (50)		NOT NULL,
	[SubscriptionId]					NVARCHAR (50)		NULL,
	[VhfFrequency]						NVARCHAR (50)		NULL,
	[CollarTypeId]						INT					NULL,
	[JobNumber]							NVARCHAR (50)		NULL,
	[Model]								NVARCHAR (50)		NULL,
	[CollarStatusId]					INT					NULL,
	[CollarMalfunctionId]				INT					NULL,
	[CollarRegionId]					INT					NULL,
	[CollarStateId]						INT					NULL,
	[InactiveDate]						DATETIME			NULL,
	[DeploymentDate]					DATETIME			NULL,
	[ProjectId]							INT					NULL,
	[Size]								NVARCHAR (50)		NULL,
	[BeltingColour]						NVARCHAR (50)		NULL,
	[FirmwareVersion]					NVARCHAR (MAX)		NULL,
	[Comments]							NVARCHAR (MAX)		NULL,
	[DropOffDate]						DATETIME			NULL,
	[EstimatedDropOff]					DATETIME			NULL,
	[EstimatedGpsFailure]				DATETIME			NULL,
	[EstimatedGpsBatteryEnd]			DATETIME			NULL,
	[EstimatedVhfFailure]				DATETIME			NULL,
	[EstimatedVhfBatteryEnd]			DATETIME			NULL,

	[SpeciesId]							INT					NULL,
	[AnimalStatusId]					INT					NULL,
	[AnimalId]							INT					NULL,
	[EstimatedYearOfBirth]				INT				    NULL,
	[EstimatedYearOfBirthBy]			NVARCHAR (50)	    NULL,
	[AgeClassId]						INT					NULL,
	[EstimatedYearOfBirthMethod]		NVARCHAR (50)		NULL,
	[AnimalSexId]						INT					NULL,

	[HerdPopulationId]					INT					NULL,
	[HerdAssociationConfidenceLevelId]	INT					NULL,
	[HerdAssociationMethodId]			INT					NULL,
	[HerdAssociationDate]				DATETIME			NULL,
	
	[BreedingStatusId]					INT					NULL,
	[BreedingStatusConfidenceLevelId]	INT					NULL,
	[BreedingStatusMethodId]			INT					NULL,
	[BreedingStatusDate]				DATETIME			NULL,

	[AnimalMortalityId]					INT					NULL,
	[MortalityDate]						DATETIME			NULL,
	[MortalityConfidenceId]				INT					NULL,
	[MortalityLatitude]					FLOAT				NULL,
	[MortalityLongitude]				FLOAT				NULL,
	[BodyCondition]						NVARCHAR (MAX)		NULL,
	[CarcassPosition]					NVARCHAR (50)		NULL,
	[CarcassComments]					NVARCHAR (MAX)		NULL,

	[SignsOfPredation]					BIT					NULL,
	[EvidenceOfChase]					BIT				    NULL,
	[SignsOfScavengers]					BIT				    NULL,
	[SnowSinceDeath]					BIT				    NULL,
	[SignsOfHumans]						BIT				    NULL,
	[LastUpdated]						DATETIME		    NOT NULL DEFAULT GETUTCDATE(),

	CONSTRAINT [PK_CollaredAnimals] PRIMARY KEY CLUSTERED ([CollaredAnimalId]),
	CONSTRAINT [FK_CollaredAnimals_CollarMalfunctions] FOREIGN KEY ([CollarMalfunctionId]) REFERENCES [dbo].[CollarMalfunctions] ([CollarMalfunctionId]),
	CONSTRAINT [FK_CollaredAnimals_CollarStates] FOREIGN KEY ([CollarStateId]) REFERENCES [dbo].[CollarStates] ([CollarStateId]),
	CONSTRAINT [FK_CollaredAnimals_CollarStatuses] FOREIGN KEY ([CollarStatusId]) REFERENCES [dbo].[CollarStatuses] ([CollarStatusId]),
	CONSTRAINT [FK_CollaredAnimals_CollarRegions] FOREIGN KEY ([CollarRegionId]) REFERENCES [dbo].[CollarRegions] ([CollarRegionId]),
	CONSTRAINT [FK_CollaredAnimals_CollarTypes] FOREIGN KEY ([CollarTypeId]) REFERENCES [dbo].[CollarTypes] ([CollarTypeId]),
	CONSTRAINT [FK_CollaredAnimals_Project] FOREIGN KEY ([ProjectId]) REFERENCES [dbo].[Project] ([ProjectId]),
	CONSTRAINT [FK_CollaredAnimals_AnimalMortalities] FOREIGN KEY ([AnimalMortalityId]) REFERENCES [dbo].[AnimalMortalities] ([AnimalMortalityId]),
	CONSTRAINT [FK_CollaredAnimals_ConfidenceLevels_Mortality] FOREIGN KEY ([MortalityConfidenceId]) REFERENCES [dbo].[ConfidenceLevels] ([ConfidenceLevelId]),
	CONSTRAINT [FK_CollaredAnimals_Species] FOREIGN KEY ([SpeciesId]) REFERENCES [dbo].[Species] ([SpeciesId]),
	CONSTRAINT [FK_CollaredAnimals_AnimalStatuses] FOREIGN KEY ([AnimalStatusId]) REFERENCES [dbo].[AnimalStatuses] ([AnimalStatusId]),
	CONSTRAINT [FK_CollaredAnimals_HerdPopulations] FOREIGN KEY ([HerdPopulationId]) REFERENCES [dbo].[HerdPopulations] ([HerdPopulationId]),
	CONSTRAINT [FK_CollaredAnimals_ConfidenceLevels_HerdAssociation] FOREIGN KEY ([HerdAssociationConfidenceLevelId]) REFERENCES [dbo].[ConfidenceLevels] ([ConfidenceLevelId]),
	CONSTRAINT [FK_CollaredAnimals_HerdAssociationMethods] FOREIGN KEY ([HerdAssociationMethodId]) REFERENCES [dbo].[HerdAssociationMethods] ([HerdAssociationMethodId]),
	CONSTRAINT [FK_CollaredAnimals_BreedingStatuses] FOREIGN KEY ([BreedingStatusId]) REFERENCES [dbo].[BreedingStatuses] ([BreedingStatusId]),
	CONSTRAINT [FK_CollaredAnimals_ConfidenceLevels_BreedingStatus] FOREIGN KEY ([BreedingStatusConfidenceLevelId]) REFERENCES [dbo].[ConfidenceLevels] ([ConfidenceLevelId]),
	CONSTRAINT [FK_CollaredAnimals_BreedingStatusMethods] FOREIGN KEY ([BreedingStatusMethodId]) REFERENCES [dbo].[BreedingStatusMethods] ([BreedingStatusMethodId])
)
