CREATE TABLE [dbo].[Project]
(
	[ProjectId] INT NOT NULL IDENTITY , 
    [Name] NVARCHAR(250) NOT NULL, 
	[ProjectNumber] NVARCHAR(250) NULL, 
    [LeadRegionId] INT NULL, 
    [ProjectStatusId] INT NULL, 
    [StatusDate] DATE NULL, 
    [ProjectLeadId] INT NULL, 
    [StartDate] DATE NULL, 
    [EndDate] DATE NULL, 
    [IsSensitiveData] BIT NULL, 
    [Description] NVARCHAR(MAX) NULL, 
    [Objectives] NVARCHAR(MAX) NULL, 
    [StudyArea] NVARCHAR(MAX) NULL, 
    [Methods] NVARCHAR(MAX) NULL, 
    [Comments] NVARCHAR(MAX) NULL, 
    [Results] NVARCHAR(MAX) NULL, 
    [TermsAndConditions] NVARCHAR(MAX) NULL, 
    [LastUpdated] DATETIME NOT NULL, 
    [WildlifeResearchPermitNumber] NVARCHAR(250) NULL, 
    CONSTRAINT [PK_Project] PRIMARY KEY ([ProjectId]), 
    CONSTRAINT [FK_Project_LeadRegion] FOREIGN KEY ([LeadRegionId]) REFERENCES dbo.[LeadRegion]([LeadRegionId]), 
    CONSTRAINT [FK_Project_ProjectStatus] FOREIGN KEY ([ProjectStatusId]) REFERENCES dbo.[ProjectStatus]([ProjectStatusId]), 
    CONSTRAINT [FK_Project_ProjectLead] FOREIGN KEY ([ProjectLeadId]) REFERENCES dbo.[Person]([PersonId])
)
