CREATE TABLE [dbo].[Species]
(
	[SpeciesId]                                    INT               NOT NULL IDENTITY,
	[Name]                                         NVARCHAR (50)     NOT NULL,
	[CommonName]                                   NVARCHAR (50)     NULL,
	[SubSpeciesName]                               NVARCHAR (50)     NULL,
	[EcoType]                                      NVARCHAR (50)     NULL,
	[Population]                                   NVARCHAR (50)     NULL,
	[NSGlobalId]                                   NVARCHAR (50)     NULL,
	[NSNWTId]                                      NVARCHAR (50)     NULL,
	[ELCODE]                                       NVARCHAR (50)     NULL,
	[KingdomTaxonomyId]                            INT               NULL,
	[PhylumTaxonomyId]                             INT               NULL,
	[SubPhylumTaxonomyId]                          INT               NULL,
	[ClassTaxonomyId]                              INT               NULL,
	[SubClassTaxonomyId]                           INT               NULL,
	[OrderTaxonomyId]                              INT               NULL,
	[SubOrderTaxonomyId]                           INT               NULL,
	[InfraOrderTaxonomyId]                         INT               NULL,
	[SuperFamilyTaxonomyId]                        INT               NULL,
	[FamilyTaxonomyId]                             INT               NULL,
	[SubFamilyTaxonomyId]                          INT               NULL,
	[GroupTaxonomyId]					           INT               NULL,
	[NonNTSpecies]                                 BIT               NULL,
	[CanadaKnownSubSpeciesCount]                   INT               NULL,
	[CanadaKnownSubSpeciesDescription]             NVARCHAR (MAX)    NULL,
	[NWTKnownSubSpeciesCount]                      INT               NULL,
	[NWTKnownSubSpeciesDescription]                NVARCHAR (MAX)    NULL,
	[AgeOfMaturity]                                INT               NULL,
    [AgeOfMaturityDescription]                     NVARCHAR (MAX)    NULL,
    [ReproductionFrequencyPerYear]                 INT               NULL,
    [ReproductionFrequencyPerYearDescription]      NVARCHAR (MAX)    NULL,
    [Longevity]                                    INT               NULL,
    [LongevityDescription]                         NVARCHAR (MAX)    NULL,
    [VegetationReproductionDescription]            NVARCHAR (MAX)    NULL,
    [HostFishDescription]                          NVARCHAR (MAX)    NULL,
    [OtherReproductionDescription]                 NVARCHAR (MAX)    NULL,
	[EcozoneDescription]                           NVARCHAR (MAX)    NULL,
	[EcoregionDescription]                         NVARCHAR (MAX)    NULL,
	[ProtectedAreaDescription]                     NVARCHAR (MAX)    NULL,
	[RangeExtentScore]                             NVARCHAR (5)      NULL,
	[RangeExtentDescription]                       NVARCHAR (MAX)    NULL,
	[DistributionPercentage]                       NVARCHAR (50)     NULL,
	[AreaOfOccupancyScore]                         NVARCHAR (5)      NULL,
	[AreaOfOccupancyDescription]                   NVARCHAR (MAX)    NULL,
	[HistoricalDistributionDescription]            NVARCHAR (MAX)    NULL,
	[MarineDistributionDescription]                NVARCHAR (MAX)    NULL,
	[WinterDistributionDescription]                NVARCHAR (MAX)    NULL,
	[HabitatDescription]                           NVARCHAR (MAX)    NULL,
	[EnvironmentalSpecificityScore]                NVARCHAR (5)      NULL,
	[EnvironmentalSpecificityDescription]          NVARCHAR (MAX)    NULL,
	[PopulationSizeScore]                          NVARCHAR (5)      NULL,
	[PopulationSizeDescription]                    NVARCHAR (MAX)    NULL,
	[NumberOfOccurencesScore]                      NVARCHAR (5)      NULL,
	[NumberOfOccurencesDescription]                NVARCHAR (MAX)    NULL,
	[DensityDescription]                           NVARCHAR (MAX)    NULL,
	[ThreatsScore]                                 NVARCHAR (5)      NULL,
	[ThreatsDescription]                           NVARCHAR (MAX)    NULL,
	[IntrinsicVulnerabilityScore]                  NVARCHAR (5)      NULL,
	[IntrinsicVulnerabilityDescription]            NVARCHAR (MAX)    NULL,
	[ShortTermTrendsScore]                         NVARCHAR (5)      NULL,
	[ShortTermTrendsDescription]                   NVARCHAR (MAX)    NULL,
	[LongTermTrendsScore]                          NVARCHAR (5)      NULL,
	[LongTermTrendsDescription]                    NVARCHAR (MAX)    NULL,
	[StatusRankId]                                 INT               NULL,
	[StatusRankDescription]                        NVARCHAR (MAX)    NULL,
	[SRank]                                        NVARCHAR (50)     NULL,
	[DecisionProcessDescription]                   NVARCHAR (MAX)    NULL,
	[EconomicStatusDescription]                    NVARCHAR (MAX)    NULL,
	[COSEWICStatusId]                              INT               NULL,
	[COSEWICStatusDescription]                     NVARCHAR (MAX)    NULL,
	[NRank]                                        NVARCHAR (50)     NULL,
	[SARAStatus]                                   NVARCHAR (50)     NULL,
	[FederalSpeciesAtRiskStatusDescription]        NVARCHAR (MAX)    NULL,
	[NWTSARCAssessmentDescription]                 NVARCHAR (MAX)    NULL,
	[NWTStatusRank]                                NVARCHAR (50)     NULL,
	[NWTSpeciesAtRiskStatusDescription]            NVARCHAR (MAX)    NULL,
	[CanadianConservationSignificanceDescription]  NVARCHAR (MAX)    NULL,
	[IUCNStatus]                                   NVARCHAR (50)     NULL,
	[GRank]                                        NVARCHAR (50)     NULL,
	[IUCNDescription]                              NVARCHAR (50)     NULL,
	CONSTRAINT [PK_Species] PRIMARY KEY CLUSTERED ([SpeciesId]),
	CONSTRAINT [UK_Species_Name] UNIQUE ([Name]),
	CONSTRAINT [FK_Species_Taxonomy_Kingdom] FOREIGN KEY ([KingdomTaxonomyId]) REFERENCES [dbo].[Taxonomy] ([TaxonomyId]),
	CONSTRAINT [FK_Species_Taxonomy_Phylum] FOREIGN KEY ([PhylumTaxonomyId]) REFERENCES [dbo].[Taxonomy] ([TaxonomyId]),
	CONSTRAINT [FK_Species_Taxonomy_SubPhylum] FOREIGN KEY ([SubPhylumTaxonomyId]) REFERENCES [dbo].[Taxonomy] ([TaxonomyId]),
	CONSTRAINT [FK_Species_Taxonomy_Class] FOREIGN KEY ([ClassTaxonomyId]) REFERENCES [dbo].[Taxonomy] ([TaxonomyId]),
	CONSTRAINT [FK_Species_Taxonomy_SubClass] FOREIGN KEY ([SubClassTaxonomyId]) REFERENCES [dbo].[Taxonomy] ([TaxonomyId]),
	CONSTRAINT [FK_Species_Taxonomy_Order] FOREIGN KEY ([OrderTaxonomyId]) REFERENCES [dbo].[Taxonomy] ([TaxonomyId]),
	CONSTRAINT [FK_Species_Taxonomy_SubOrder] FOREIGN KEY ([SubOrderTaxonomyId]) REFERENCES [dbo].[Taxonomy] ([TaxonomyId]),
	CONSTRAINT [FK_Species_Taxonomy_InfraOrder] FOREIGN KEY ([InfraOrderTaxonomyId]) REFERENCES [dbo].[Taxonomy] ([TaxonomyId]),
	CONSTRAINT [FK_Species_Taxonomy_SuperFamily] FOREIGN KEY ([SuperFamilyTaxonomyId]) REFERENCES [dbo].[Taxonomy] ([TaxonomyId]),
	CONSTRAINT [FK_Species_Taxonomy_Family] FOREIGN KEY ([FamilyTaxonomyId]) REFERENCES [dbo].[Taxonomy] ([TaxonomyId]),
	CONSTRAINT [FK_Species_Taxonomy_SubFamily] FOREIGN KEY ([SubFamilyTaxonomyId]) REFERENCES [dbo].[Taxonomy] ([TaxonomyId]),
	CONSTRAINT [FK_Species_Taxonomy_Group] FOREIGN KEY ([GroupTaxonomyId]) REFERENCES [dbo].[Taxonomy] ([TaxonomyId]),
	CONSTRAINT [FK_Species_StatusRanks] FOREIGN KEY ([StatusRankId]) REFERENCES [dbo].[StatusRanks] ([StatusRankId]),
	CONSTRAINT [FK_Species_COSEWICStatus] FOREIGN KEY ([COSEWICStatusId]) REFERENCES [dbo].[COSEWICStatus] ([COSEWICStatusId])
)
