CREATE TABLE [dbo].[Wildlife_Animal_Disease_NWT]
(
	[Id] INT NOT NULL PRIMARY KEY,
	[CaseNumber] [nvarchar](50) NULL,
	[NecropsyNumber] [nvarchar](50) NULL,
	[DateCollected] [datetime] NULL,
	[DateReported] [datetime] NULL,
	[NecropsyDate] [datetime] NULL,
	[ReportType] [nvarchar](50) NULL,
	[LaboratoryName] [nvarchar](100) NULL,
	[LaboratoryID] [nvarchar](50) NULL,
	[LabReportStatus] [nvarchar](50) NULL,
	[FieldLocation] [nvarchar](50) NULL,
	[latitude] [float] NULL,
	[Latitudedd] [float] NULL,
	[lattitudemm] [float] NULL,
	[longitude] [float] NULL,
	[Longitudedd] [float] NULL,
	[longitudemm] [float] NULL,
	[Community] [nvarchar](50) NULL,
	[Region] [nvarchar](50) NULL,
	[GeographicRegion] [nvarchar](50) NULL,
	[Species] [nvarchar](50) NULL,
	[Population] [nvarchar](50) NULL,
	[NumberAffected] [float] NULL,
	[NumberSampled] [float] NULL,
	[Age] [nvarchar](50) NULL,
	[Sex] [nvarchar](50) NULL,
	[AnimalHistory] [nvarchar](max) NULL,
	[BodySystem1] [nvarchar](500) NULL,
	[BodySystem2] [nvarchar](500) NULL,
	[TissueCollected1] [nvarchar](500) NULL,
	[TissueCollected2] [nvarchar](500) NULL,
	[TissueCollected3] [nvarchar](500) NULL,
	[DiseaseProcess1] [nvarchar](500) NULL,
	[DiseaseProcess2] [nvarchar](500) NULL,
	[MorphologicalDiagnosis1] [nvarchar](500) NULL,
	[MorphologicalDiagnosis2] [nvarchar](500) NULL,
	[MorphologicalDiagnosis3] [nvarchar](500) NULL,
	[EtiologicAgent1] [nvarchar](500) NULL,
	[EtiologicAgent2] [nvarchar](500) NULL,
	[EtiologicAgent3] [nvarchar](500) NULL,
	[EtiologicAgent4] [nvarchar](500) NULL,
	[PreliminaryDiagnosis] [nvarchar](500) NULL,
	[FinalDiagnosis1] [nvarchar](500) NULL,
	[FinalDiagnosis2] [nvarchar](500) NULL,
	[FinalDiagnosis3] [nvarchar](500) NULL,
	[Comments] [nvarchar](max) NULL,
	[Histopathology] [nvarchar](max) NULL,
	[Interpretation ] [nvarchar](500) NULL,
	[Finder_submitter ] [nvarchar](100) NULL
)
