
CREATE PROCEDURE [dbo].[WolfNecropsy_Save]
	@p_caseId INT,
	@p_NecropsyId NVARCHAR(30),
	@p_CommonName nvarchar(30)  =  NULL,
	@p_SpeciesId int =  NULL,
	@p_NecropsyDate  date = NULL,
	@p_Sex nvarchar(10)  =  NULL,
	@p_Location nvarchar(50)  =  NULL,
	@p_GridCell int =  NULL,
	@p_DateReceived date = NULL,
	@p_DateKilled date = NULL,
	@p_AgeClass nvarchar(10)  =  NULL,
	@p_AgeEstimated float =  NULL,
	@p_Submitter nvarchar(50)  =  NULL,
	@p_ContactInfo nvarchar(50)  =  NULL,
	@p_RegionId int =  NULL,
	@p_MethodKilled nvarchar(30)  =  NULL,
	@p_Injuries bit =  NULL,
	@p_TagComments nvarchar(max)  =  NULL,
	@p_TagReCheck bit =  NULL,
	@p_BodyWt_unskinned float =  NULL,
	@p_NeckGirth_unsk float =  NULL,
	@p_ChestGirth_unsk float =  NULL,
	@p_Contour_Nose_Tail float =  NULL,
	@p_Tail_Length float =  NULL,
	@p_BodyWt_skinned float =  NULL,
	@p_PeltWt float =  NULL,
	@p_NeckGirth_sk float =  NULL,
	@p_ChestGirth_sk float =  NULL,
	@p_RumpFat float =  NULL,
	@p_TotalRank_Ext float =  NULL,
	@p_Tongue bit =  NULL,
	@p_HairCollected bit =  NULL,
	@p_SkullCollected bit =  NULL,
	@p_HindLegMuscle_StableIsotopes bit =  NULL,
	@p_HindLegMuscle_Contaminants bit =  NULL,
	@p_Femur bit =  NULL,
	@p_Feces bit =  NULL,
	@p_Diaphragm bit =  NULL,
	@p_Lung bit =  NULL,
	@p_Liver_DNA bit =  NULL,
	@p_Liver_SIA bit =  NULL,
	@p_Liver_Contam bit =  NULL,
	@p_Spleen bit =  NULL,
	@p_KidneyL bit =  NULL,
	@p_KidneyL_wt float =  NULL,
	@p_KidneyR bit =  NULL,
	@p_KidneyR_wt float =  NULL,
	@p_Blood_tabs bit =  NULL,
	@p_Blood_tubes bit =  NULL,
	@p_Stomach bit =  NULL,
	@p_StomachCont bit =  NULL,
	@p_Stomach_Full bit =  NULL,
	@p_Stomach_Empty bit =  NULL,
	@p_StomachCont_wt float =  NULL,
	@p_StomachContentDesc nvarchar(max)  =  NULL,
	@p_intestinalTract bit =  NULL,
	@p_UterineScars int =  NULL,
	@p_Uterus bit =  NULL,
	@p_Ovaries bit =  NULL,
	@p_LymphNodes bit =  NULL,
	@p_Others bit =  NULL,
	@p_internalRank int =  NULL,
	@p_PeltColor nvarchar(20)  =  NULL,
	@p_BackFat bit =  NULL,
	@p_SternumFat bit =  NULL,
	@p_InguinalFat bit =  NULL,
	@p_Incentive bit =  NULL,
	@p_IncentiveAmt float =  NULL,
	@p_Conflict bit =  NULL,
	@p_GroupSize int =  NULL,
	@p_PackId nvarchar(50)  =  NULL,
	@p_Xiphoid bit =  NULL,
	@p_Personnel nvarchar(50)  =  NULL,
	@p_Pictures bit =  NULL,
	@p_SpeciesComments nvarchar(max)  =  NULL,
	@p_TagInjuryComments nvarchar(max)  =  NULL,
	@p_InjuryComments nvarchar(max)  =  NULL,
	@p_ExamInjuryComments nvarchar(max)  =  NULL,
	@p_ExamComments nvarchar(max)  =  NULL,
	@p_PicturesComments nvarchar(max)  =  NULL,
	@p_MeasurementsComments nvarchar(max)  =  NULL,
	@p_MissingPartsComments nvarchar(max)  =  NULL,
	@p_StomachContents nvarchar(max)  =  NULL,
	@p_OtherSamplesComments nvarchar(max)  =  NULL,
	@p_SamplesComments nvarchar(max)  =  NULL,
	@p_GeneralComments nvarchar(max)  =  NULL
AS
	IF(@p_caseId IS NULL)
	BEGIN
		INSERT INTO 
			dbo.[WolfNecropsy] (NecropsyId,	CommonName,	SpeciesId,	NecropsyDate,	Sex,	[Location],	GridCell,	DateReceived,	DateKilled,	AgeClass,	AgeEstimated,	Submitter,	ContactInfo,	RegionId,	MethodKilled,	Injuries,	TagComments,	TagReCheck,	BodyWt_unskinned,	NeckGirth_unsk,	ChestGirth_unsk,	Contour_Nose_Tail,	Tail_Length,	BodyWt_skinned,	PeltWt,	NeckGirth_sk,	ChestGirth_sk,	RumpFat,	TotalRank_Ext,	Tongue,	HairCollected,	SkullCollected,	HindLegMuscle_StableIsotopes,	HindLegMuscle_Contaminants,	Femur,	Feces,	Diaphragm,	Lung,	Liver_DNA,	Liver_SIA,	Liver_Contam,	Spleen,	KidneyL,	KidneyL_wt,	KidneyR,	KidneyR_wt,	Blood_tabs,	Blood_tubes,	Stomach,	StomachCont,	Stomach_Full,	Stomach_Empty,	StomachCont_wt,	StomachContentDesc,	IntestinalTract,	UterineScars,	Uterus,	Ovaries,	LymphNodes,	Others,	InternalRank,	PeltColor,	BackFat,	SternumFat,	InguinalFat,	Incentive,	IncentiveAmt,	Conflict,	GroupSize,	PackId,	Xiphoid,	Personnel,	Pictures,	SpeciesComments,	TagInjuryComments,	InjuryComments,	ExamInjuryComments,	ExamComments,	PicturesComments,	MeasurementsComments,	MissingPartsComments,	StomachContents,	OtherSamplesComments,	SamplesComments,GeneralComments)
		VALUES
			(@p_NecropsyId,	@p_CommonName,	@p_SpeciesId,	@p_NecropsyDate,	@p_Sex,	@p_Location,	@p_GridCell,	@p_DateReceived,	@p_DateKilled,	@p_AgeClass,	@p_AgeEstimated,	@p_Submitter,	@p_ContactInfo,	@p_RegionId,	@p_MethodKilled,	@p_Injuries,	@p_TagComments,	@p_TagReCheck,	@p_BodyWt_unskinned,	@p_NeckGirth_unsk,	@p_ChestGirth_unsk,	@p_Contour_Nose_Tail,	@p_Tail_Length,	@p_BodyWt_skinned,	@p_PeltWt,	@p_NeckGirth_sk,	@p_ChestGirth_sk,	@p_RumpFat,	@p_TotalRank_Ext,	@p_Tongue,	@p_HairCollected,	@p_SkullCollected,	@p_HindLegMuscle_StableIsotopes,	@p_HindLegMuscle_Contaminants,	@p_Femur,	@p_Feces,	@p_Diaphragm,	@p_Lung,	@p_Liver_DNA,	@p_Liver_SIA,	@p_Liver_Contam,	@p_Spleen,	@p_KidneyL,	@p_KidneyL_wt,	@p_KidneyR,	@p_KidneyR_wt,	@p_Blood_tabs,	@p_Blood_tubes,	@p_Stomach,	@p_StomachCont,	@p_Stomach_Full,	@p_Stomach_Empty,	@p_StomachCont_wt,	@p_StomachContentDesc,	@p_IntestinalTract,	@p_UterineScars,	@p_Uterus,	@p_Ovaries,	@p_LymphNodes,	@p_Others,	@p_InternalRank,	@p_PeltColor,	@p_BackFat,	@p_SternumFat,	@p_InguinalFat,	@p_Incentive,	@p_IncentiveAmt,	@p_Conflict,	@p_GroupSize,	@p_PackId,	@p_Xiphoid,	@p_Personnel,	@p_Pictures,	@p_SpeciesComments,	@p_TagInjuryComments,	@p_InjuryComments,	@p_ExamInjuryComments,	@p_ExamComments,	@p_PicturesComments,	@p_MeasurementsComments,	@p_MissingPartsComments,	@p_StomachContents,	@p_OtherSamplesComments,	@p_SamplesComments,	@p_GeneralComments)
	END
	ELSE
	BEGIN
		UPDATE
			dbo.[WolfNecropsy]
		SET
			NecropsyId = @p_NecropsyId,
			CommonName = @p_CommonName,
			SpeciesId = @p_SpeciesId,
			NecropsyDate = @p_NecropsyDate,
			Sex = @p_Sex,
			[Location] = @p_Location,
			GridCell = @p_GridCell,
			DateReceived = @p_DateReceived,
			DateKilled = @p_DateKilled,
			AgeClass = @p_AgeClass,
			AgeEstimated = @p_AgeEstimated,
			Submitter = @p_Submitter,
			ContactInfo = @p_ContactInfo,
			RegionId = @p_RegionId,
			MethodKilled = @p_MethodKilled,
			Injuries = @p_Injuries,
			TagComments = @p_TagComments,
			TagReCheck = @p_TagReCheck,
			BodyWt_unskinned = @p_BodyWt_unskinned,
			NeckGirth_unsk = @p_NeckGirth_unsk,
			ChestGirth_unsk = @p_ChestGirth_unsk,
			Contour_Nose_Tail = @p_Contour_Nose_Tail,
			Tail_Length = @p_Tail_Length,
			BodyWt_skinned = @p_BodyWt_skinned,
			PeltWt = @p_PeltWt,
			NeckGirth_sk = @p_NeckGirth_sk,
			ChestGirth_sk = @p_ChestGirth_sk,
			RumpFat = @p_RumpFat,
			TotalRank_Ext = @p_TotalRank_Ext,
			Tongue = @p_Tongue,
			HairCollected = @p_HairCollected,
			SkullCollected = @p_SkullCollected,
			HindLegMuscle_StableIsotopes = @p_HindLegMuscle_StableIsotopes,
			HindLegMuscle_Contaminants = @p_HindLegMuscle_Contaminants,
			Femur = @p_Femur,
			Feces = @p_Feces,
			Diaphragm = @p_Diaphragm,
			Lung = @p_Lung,
			Liver_DNA = @p_Liver_DNA,
			Liver_SIA = @p_Liver_SIA,
			Liver_Contam = @p_Liver_Contam,
			Spleen = @p_Spleen,
			KidneyL = @p_KidneyL,
			KidneyL_wt = @p_KidneyL_wt,
			KidneyR = @p_KidneyR,
			KidneyR_wt = @p_KidneyR_wt,
			Blood_tabs = @p_Blood_tabs,
			Blood_tubes = @p_Blood_tubes,
			Stomach = @p_Stomach,
			StomachCont = @p_StomachCont,
			Stomach_Full = @p_Stomach_Full,
			Stomach_Empty = @p_Stomach_Empty,
			StomachCont_wt = @p_StomachCont_wt,
			StomachContentDesc = @p_StomachContentDesc,
			IntestinalTract = @p_IntestinalTract,
			UterineScars = @p_UterineScars,
			Uterus = @p_Uterus,
			Ovaries = @p_Ovaries,
			LymphNodes = @p_LymphNodes,
			Others = @p_Others,
			InternalRank = @p_InternalRank,
			PeltColor = @p_PeltColor,
			BackFat = @p_BackFat,
			SternumFat = @p_SternumFat,
			InguinalFat = @p_InguinalFat,
			Incentive = @p_Incentive,
			IncentiveAmt = @p_IncentiveAmt,
			Conflict = @p_Conflict,
			GroupSize = @p_GroupSize,
			PackId = @p_PackId,
			Xiphoid = @p_Xiphoid,
			Personnel = @p_Personnel,
			Pictures = @p_Pictures,
			SpeciesComments = @p_SpeciesComments,
			TagInjuryComments = @p_TagInjuryComments,
			InjuryComments = @p_InjuryComments,
			ExamInjuryComments = @p_ExamInjuryComments,
			ExamComments = @p_ExamComments,
			PicturesComments = @p_PicturesComments,
			MeasurementsComments = @p_MeasurementsComments,
			MissingPartsComments = @p_MissingPartsComments,
			StomachContents = @p_StomachContents,
			OtherSamplesComments = @p_OtherSamplesComments,
			SamplesComments = @p_SamplesComments,
			GeneralComments = @p_GeneralComments
		WHERE
			CaseId = @p_caseId
	END

RETURN 0

GRANT EXECUTE ON [dbo].[WolfNecropsy_Save] TO [WMISUser]
GO


