CREATE PROCEDURE [dbo].[WolfNecropsy_Get]
	@p_caseId INT
AS
	SELECT TOP 1
	p.NecropsyId,
	p.CommonName,
	p.SpeciesId,
	p.NecropsyDate,
	p.Sex,
	p.Location,
	p.GridCell,
	p.DateReceived,
	p.DateKilled,
	p.AgeClass,
	p.AgeEstimated,
	p.Submitter,
	p.ContactInfo,
	p.RegionId,
	p.MethodKilled,
	p.Injuries,
	p.TagComments,
	p.TagReCheck,
	p.BodyWt_unskinned,
	p.NeckGirth_unsk,
	p.ChestGirth_unsk,
	p.Contour_Nose_Tail,
	p.Tail_Length,
	p.BodyWt_skinned,
	p.PeltWt,
	p.NeckGirth_sk,
	p.ChestGirth_sk,
	p.RumpFat,
	p.TotalRank_Ext,
	p.Tongue,
	p.HairCollected,
	p.SkullCollected,
	p.HindLegMuscle_StableIsotopes,
	p.HindLegMuscle_Contaminants,
	p.Femur,
	p.Feces,
	p.Diaphragm,
	p.Lung,
	p.Liver_DNA,
	p.Liver_SIA,
	p.Liver_Contam,
	p.Spleen,
	p.KidneyL,
	p.KidneyL_wt,
	p.KidneyR,
	p.KidneyR_wt,
	p.Blood_tabs,
	p.Blood_tubes,
	p.Stomach,
	p.StomachCont,
	p.Stomach_Full,
	p.Stomach_Empty,
	p.StomachCont_wt,
	p.StomachContentDesc,
	p.intestinalTract,
	p.UterineScars,
	p.Uterus,
	p.Ovaries,
	p.LymphNodes,
	p.Others,
	p.internalRank,
	p.PeltColor,
	p.BackFat,
	p.SternumFat,
	p.InguinalFat,
	p.Incentive,
	p.IncentiveAmt,
	p.Conflict,
	p.GroupSize,
	p.PackId,
	p.Xiphoid,
	p.Personnel,
	p.Pictures,
	p.SpeciesComments,
	p.TagInjuryComments,
	p.InjuryComments,
	p.ExamInjuryComments,
	p.ExamComments,
	p.PicturesComments,
	p.MeasurementsComments,
	p.MissingPartsComments,
	p.StomachContents,
	p.OtherSamplesComments,
	p.SamplesComments,
	p.GeneralComments,
	p.LastUpdated


	FROM
		dbo.WolfNecropsy p
			
	WHERE
		p.CaseId =  @p_caseId

RETURN 0

GRANT EXECUTE ON [dbo].[WolfNecropsy_Get] TO [WMISUser]
GO
