//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.33440.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class ArgosData {
    
    private program[] programField;
    
    private string[] errorsField;
    
    private string versionField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("program", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public program[] program {
        get {
            return this.programField;
        }
        set {
            this.programField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlArrayItemAttribute("error", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
    public string[] errors {
        get {
            return this.errorsField;
        }
        set {
            this.errorsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string version {
        get {
            return this.versionField;
        }
        set {
            this.versionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class program {
    
    private int programNumberField;
    
    private bool programNumberFieldSpecified;
    
    private platform[] platformField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public int programNumber {
        get {
            return this.programNumberField;
        }
        set {
            this.programNumberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool programNumberSpecified {
        get {
            return this.programNumberFieldSpecified;
        }
        set {
            this.programNumberFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("platform", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public platform[] platform {
        get {
            return this.platformField;
        }
        set {
            this.platformField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class platform {
    
    private int platformIdField;
    
    private bool platformIdFieldSpecified;
    
    private string platformTypeField;
    
    private string platformNameField;
    
    private string platformModelField;
    
    private string platformHexIdField;
    
    private satellitePass[] satellitePassField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public int platformId {
        get {
            return this.platformIdField;
        }
        set {
            this.platformIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool platformIdSpecified {
        get {
            return this.platformIdFieldSpecified;
        }
        set {
            this.platformIdFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string platformType {
        get {
            return this.platformTypeField;
        }
        set {
            this.platformTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string platformName {
        get {
            return this.platformNameField;
        }
        set {
            this.platformNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string platformModel {
        get {
            return this.platformModelField;
        }
        set {
            this.platformModelField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string platformHexId {
        get {
            return this.platformHexIdField;
        }
        set {
            this.platformHexIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("satellitePass", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public satellitePass[] satellitePass {
        get {
            return this.satellitePassField;
        }
        set {
            this.satellitePassField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class satellitePass {
    
    private string satelliteField;
    
    private System.DateTime bestMsgDateField;
    
    private bool bestMsgDateFieldSpecified;
    
    private int durationField;
    
    private bool durationFieldSpecified;
    
    private int nbMessageField;
    
    private bool nbMessageFieldSpecified;
    
    private int message120Field;
    
    private bool message120FieldSpecified;
    
    private int bestLevelField;
    
    private bool bestLevelFieldSpecified;
    
    private double frequencyField;
    
    private bool frequencyFieldSpecified;
    
    private location locationField;
    
    private message[] messageField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string satellite {
        get {
            return this.satelliteField;
        }
        set {
            this.satelliteField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public System.DateTime bestMsgDate {
        get {
            return this.bestMsgDateField;
        }
        set {
            this.bestMsgDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool bestMsgDateSpecified {
        get {
            return this.bestMsgDateFieldSpecified;
        }
        set {
            this.bestMsgDateFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public int duration {
        get {
            return this.durationField;
        }
        set {
            this.durationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool durationSpecified {
        get {
            return this.durationFieldSpecified;
        }
        set {
            this.durationFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public int nbMessage {
        get {
            return this.nbMessageField;
        }
        set {
            this.nbMessageField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool nbMessageSpecified {
        get {
            return this.nbMessageFieldSpecified;
        }
        set {
            this.nbMessageFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public int message120 {
        get {
            return this.message120Field;
        }
        set {
            this.message120Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool message120Specified {
        get {
            return this.message120FieldSpecified;
        }
        set {
            this.message120FieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public int bestLevel {
        get {
            return this.bestLevelField;
        }
        set {
            this.bestLevelField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool bestLevelSpecified {
        get {
            return this.bestLevelFieldSpecified;
        }
        set {
            this.bestLevelFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public double frequency {
        get {
            return this.frequencyField;
        }
        set {
            this.frequencyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool frequencySpecified {
        get {
            return this.frequencyFieldSpecified;
        }
        set {
            this.frequencyFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public location location {
        get {
            return this.locationField;
        }
        set {
            this.locationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("message", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public message[] message {
        get {
            return this.messageField;
        }
        set {
            this.messageField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class location {
    
    private System.DateTime locationDateField;
    
    private bool locationDateFieldSpecified;
    
    private double latitudeField;
    
    private bool latitudeFieldSpecified;
    
    private double longitudeField;
    
    private bool longitudeFieldSpecified;
    
    private double altitudeField;
    
    private bool altitudeFieldSpecified;
    
    private string locationClassField;
    
    private float gpsSpeedField;
    
    private bool gpsSpeedFieldSpecified;
    
    private float gpsHeadingField;
    
    private bool gpsHeadingFieldSpecified;
    
    private diagnostic diagnosticField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public System.DateTime locationDate {
        get {
            return this.locationDateField;
        }
        set {
            this.locationDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool locationDateSpecified {
        get {
            return this.locationDateFieldSpecified;
        }
        set {
            this.locationDateFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public double latitude {
        get {
            return this.latitudeField;
        }
        set {
            this.latitudeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool latitudeSpecified {
        get {
            return this.latitudeFieldSpecified;
        }
        set {
            this.latitudeFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public double longitude {
        get {
            return this.longitudeField;
        }
        set {
            this.longitudeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool longitudeSpecified {
        get {
            return this.longitudeFieldSpecified;
        }
        set {
            this.longitudeFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public double altitude {
        get {
            return this.altitudeField;
        }
        set {
            this.altitudeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool altitudeSpecified {
        get {
            return this.altitudeFieldSpecified;
        }
        set {
            this.altitudeFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string locationClass {
        get {
            return this.locationClassField;
        }
        set {
            this.locationClassField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public float gpsSpeed {
        get {
            return this.gpsSpeedField;
        }
        set {
            this.gpsSpeedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool gpsSpeedSpecified {
        get {
            return this.gpsSpeedFieldSpecified;
        }
        set {
            this.gpsSpeedFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public float gpsHeading {
        get {
            return this.gpsHeadingField;
        }
        set {
            this.gpsHeadingField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool gpsHeadingSpecified {
        get {
            return this.gpsHeadingFieldSpecified;
        }
        set {
            this.gpsHeadingFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public diagnostic diagnostic {
        get {
            return this.diagnosticField;
        }
        set {
            this.diagnosticField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class diagnostic {
    
    private float latitude2Field;
    
    private bool latitude2FieldSpecified;
    
    private float longitude2Field;
    
    private bool longitude2FieldSpecified;
    
    private float altitude2Field;
    
    private bool altitude2FieldSpecified;
    
    private int indexField;
    
    private bool indexFieldSpecified;
    
    private int nopcField;
    
    private bool nopcFieldSpecified;
    
    private float errorRadiusField;
    
    private bool errorRadiusFieldSpecified;
    
    private float semiMajorField;
    
    private bool semiMajorFieldSpecified;
    
    private float semiMinorField;
    
    private bool semiMinorFieldSpecified;
    
    private float orientationField;
    
    private bool orientationFieldSpecified;
    
    private string hdopField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public float latitude2 {
        get {
            return this.latitude2Field;
        }
        set {
            this.latitude2Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool latitude2Specified {
        get {
            return this.latitude2FieldSpecified;
        }
        set {
            this.latitude2FieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public float longitude2 {
        get {
            return this.longitude2Field;
        }
        set {
            this.longitude2Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool longitude2Specified {
        get {
            return this.longitude2FieldSpecified;
        }
        set {
            this.longitude2FieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public float altitude2 {
        get {
            return this.altitude2Field;
        }
        set {
            this.altitude2Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool altitude2Specified {
        get {
            return this.altitude2FieldSpecified;
        }
        set {
            this.altitude2FieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public int index {
        get {
            return this.indexField;
        }
        set {
            this.indexField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool indexSpecified {
        get {
            return this.indexFieldSpecified;
        }
        set {
            this.indexFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public int nopc {
        get {
            return this.nopcField;
        }
        set {
            this.nopcField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool nopcSpecified {
        get {
            return this.nopcFieldSpecified;
        }
        set {
            this.nopcFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public float errorRadius {
        get {
            return this.errorRadiusField;
        }
        set {
            this.errorRadiusField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool errorRadiusSpecified {
        get {
            return this.errorRadiusFieldSpecified;
        }
        set {
            this.errorRadiusFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public float semiMajor {
        get {
            return this.semiMajorField;
        }
        set {
            this.semiMajorField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool semiMajorSpecified {
        get {
            return this.semiMajorFieldSpecified;
        }
        set {
            this.semiMajorFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public float semiMinor {
        get {
            return this.semiMinorField;
        }
        set {
            this.semiMinorField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool semiMinorSpecified {
        get {
            return this.semiMinorFieldSpecified;
        }
        set {
            this.semiMinorFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public float orientation {
        get {
            return this.orientationField;
        }
        set {
            this.orientationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool orientationSpecified {
        get {
            return this.orientationFieldSpecified;
        }
        set {
            this.orientationFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string hdop {
        get {
            return this.hdopField;
        }
        set {
            this.hdopField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class sensor {
    
    private int orderField;
    
    private bool orderFieldSpecified;
    
    private string nameField;
    
    private string valueTypeField;
    
    private string valueField;
    
    private string valueStrField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public int order {
        get {
            return this.orderField;
        }
        set {
            this.orderField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool orderSpecified {
        get {
            return this.orderFieldSpecified;
        }
        set {
            this.orderFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string valueType {
        get {
            return this.valueTypeField;
        }
        set {
            this.valueTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string valueStr {
        get {
            return this.valueStrField;
        }
        set {
            this.valueStrField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class format {
    
    private int formatOrderField;
    
    private bool formatOrderFieldSpecified;
    
    private string formatNameField;
    
    private sensor[] sensorField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public int formatOrder {
        get {
            return this.formatOrderField;
        }
        set {
            this.formatOrderField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool formatOrderSpecified {
        get {
            return this.formatOrderFieldSpecified;
        }
        set {
            this.formatOrderFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string formatName {
        get {
            return this.formatNameField;
        }
        set {
            this.formatNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("sensor", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public sensor[] sensor {
        get {
            return this.sensorField;
        }
        set {
            this.sensorField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class collect {
    
    private string typeField;
    
    private string alarmField;
    
    private string concatenatedField;
    
    private System.DateTime dateField;
    
    private bool dateFieldSpecified;
    
    private float levelField;
    
    private bool levelFieldSpecified;
    
    private double dopplerField;
    
    private bool dopplerFieldSpecified;
    
    private string rawDataField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string alarm {
        get {
            return this.alarmField;
        }
        set {
            this.alarmField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string concatenated {
        get {
            return this.concatenatedField;
        }
        set {
            this.concatenatedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public System.DateTime date {
        get {
            return this.dateField;
        }
        set {
            this.dateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool dateSpecified {
        get {
            return this.dateFieldSpecified;
        }
        set {
            this.dateFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public float level {
        get {
            return this.levelField;
        }
        set {
            this.levelField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool levelSpecified {
        get {
            return this.levelFieldSpecified;
        }
        set {
            this.levelFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public double doppler {
        get {
            return this.dopplerField;
        }
        set {
            this.dopplerField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool dopplerSpecified {
        get {
            return this.dopplerFieldSpecified;
        }
        set {
            this.dopplerFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string rawData {
        get {
            return this.rawDataField;
        }
        set {
            this.rawDataField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class message {
    
    private System.DateTime bestDateField;
    
    private bool bestDateFieldSpecified;
    
    private int compressionField;
    
    private bool compressionFieldSpecified;
    
    private collect[] collectField;
    
    private format[] formatField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public System.DateTime bestDate {
        get {
            return this.bestDateField;
        }
        set {
            this.bestDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool bestDateSpecified {
        get {
            return this.bestDateFieldSpecified;
        }
        set {
            this.bestDateFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public int compression {
        get {
            return this.compressionField;
        }
        set {
            this.compressionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool compressionSpecified {
        get {
            return this.compressionFieldSpecified;
        }
        set {
            this.compressionFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("collect", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public collect[] collect {
        get {
            return this.collectField;
        }
        set {
            this.collectField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("format", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public format[] format {
        get {
            return this.formatField;
        }
        set {
            this.formatField = value;
        }
    }
}
