//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wmis.ArgosService {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.dataxmldistribution.argos.cls.fr/types")]
    public partial class DixException : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.dataxmldistribution.argos.cls.fr/types")]
    public partial class stringResponseType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string returnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string @return {
            get {
                return this.returnField;
            }
            set {
                this.returnField = value;
                this.RaisePropertyChanged("return");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.dataxmldistribution.argos.cls.fr/types")]
    public partial class periodType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.DateTime startDateField;
        
        private System.DateTime endDateField;
        
        private bool endDateFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public System.DateTime startDate {
            get {
                return this.startDateField;
            }
            set {
                this.startDateField = value;
                this.RaisePropertyChanged("startDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public System.DateTime endDate {
            get {
                return this.endDateField;
            }
            set {
                this.endDateField = value;
                this.RaisePropertyChanged("endDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool endDateSpecified {
            get {
                return this.endDateFieldSpecified;
            }
            set {
                this.endDateFieldSpecified = value;
                this.RaisePropertyChanged("endDateSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(kmlRequestType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(xmlRequestType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(csvRequestType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.dataxmldistribution.argos.cls.fr/types")]
    public partial class baseRequestType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string usernameField;
        
        private string passwordField;
        
        private string itemField;
        
        private ItemChoiceType itemElementNameField;
        
        private int nbPassByPttField;
        
        private bool nbPassByPttFieldSpecified;
        
        private object item1Field;
        
        private referenceDateType referenceDateField;
        
        private bool referenceDateFieldSpecified;
        
        private string locClassField;
        
        private string geographicAreaField;
        
        private int compressionField;
        
        private bool compressionFieldSpecified;
        
        private bool mostRecentPassagesField;
        
        private bool mostRecentPassagesFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
                this.RaisePropertyChanged("username");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("platformId", typeof(string), Order=2)]
        [System.Xml.Serialization.XmlElementAttribute("programNumber", typeof(string), Order=2)]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
        public string Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
                this.RaisePropertyChanged("Item");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemChoiceType ItemElementName {
            get {
                return this.itemElementNameField;
            }
            set {
                this.itemElementNameField = value;
                this.RaisePropertyChanged("ItemElementName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int nbPassByPtt {
            get {
                return this.nbPassByPttField;
            }
            set {
                this.nbPassByPttField = value;
                this.RaisePropertyChanged("nbPassByPtt");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool nbPassByPttSpecified {
            get {
                return this.nbPassByPttFieldSpecified;
            }
            set {
                this.nbPassByPttFieldSpecified = value;
                this.RaisePropertyChanged("nbPassByPttSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("nbDaysFromNow", typeof(int), Order=5)]
        [System.Xml.Serialization.XmlElementAttribute("period", typeof(periodType), Order=5)]
        public object Item1 {
            get {
                return this.item1Field;
            }
            set {
                this.item1Field = value;
                this.RaisePropertyChanged("Item1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public referenceDateType referenceDate {
            get {
                return this.referenceDateField;
            }
            set {
                this.referenceDateField = value;
                this.RaisePropertyChanged("referenceDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool referenceDateSpecified {
            get {
                return this.referenceDateFieldSpecified;
            }
            set {
                this.referenceDateFieldSpecified = value;
                this.RaisePropertyChanged("referenceDateSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string locClass {
            get {
                return this.locClassField;
            }
            set {
                this.locClassField = value;
                this.RaisePropertyChanged("locClass");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string geographicArea {
            get {
                return this.geographicAreaField;
            }
            set {
                this.geographicAreaField = value;
                this.RaisePropertyChanged("geographicArea");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public int compression {
            get {
                return this.compressionField;
            }
            set {
                this.compressionField = value;
                this.RaisePropertyChanged("compression");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool compressionSpecified {
            get {
                return this.compressionFieldSpecified;
            }
            set {
                this.compressionFieldSpecified = value;
                this.RaisePropertyChanged("compressionSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public bool mostRecentPassages {
            get {
                return this.mostRecentPassagesField;
            }
            set {
                this.mostRecentPassagesField = value;
                this.RaisePropertyChanged("mostRecentPassages");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool mostRecentPassagesSpecified {
            get {
                return this.mostRecentPassagesFieldSpecified;
            }
            set {
                this.mostRecentPassagesFieldSpecified = value;
                this.RaisePropertyChanged("mostRecentPassagesSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.dataxmldistribution.argos.cls.fr/types", IncludeInSchema=false)]
    public enum ItemChoiceType {
        
        /// <remarks/>
        platformId,
        
        /// <remarks/>
        programNumber,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.dataxmldistribution.argos.cls.fr/types")]
    public enum referenceDateType {
        
        /// <remarks/>
        BEST_MSG_DATE,
        
        /// <remarks/>
        MODIFICATION_DATE,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.dataxmldistribution.argos.cls.fr/types")]
    public partial class kmlRequestType : baseRequestType {
        
        private bool displayDescriptionField;
        
        private bool displayDescriptionFieldSpecified;
        
        private bool displayDiagnosticField;
        
        private bool displayDiagnosticFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool displayDescription {
            get {
                return this.displayDescriptionField;
            }
            set {
                this.displayDescriptionField = value;
                this.RaisePropertyChanged("displayDescription");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool displayDescriptionSpecified {
            get {
                return this.displayDescriptionFieldSpecified;
            }
            set {
                this.displayDescriptionFieldSpecified = value;
                this.RaisePropertyChanged("displayDescriptionSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public bool displayDiagnostic {
            get {
                return this.displayDiagnosticField;
            }
            set {
                this.displayDiagnosticField = value;
                this.RaisePropertyChanged("displayDiagnostic");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool displayDiagnosticSpecified {
            get {
                return this.displayDiagnosticFieldSpecified;
            }
            set {
                this.displayDiagnosticFieldSpecified = value;
                this.RaisePropertyChanged("displayDiagnosticSpecified");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(csvRequestType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.dataxmldistribution.argos.cls.fr/types")]
    public partial class xmlRequestType : baseRequestType {
        
        private bool displayLocationField;
        
        private bool displayLocationFieldSpecified;
        
        private bool displayDiagnosticField;
        
        private bool displayDiagnosticFieldSpecified;
        
        private bool displayMessageField;
        
        private bool displayMessageFieldSpecified;
        
        private bool displayCollectField;
        
        private bool displayCollectFieldSpecified;
        
        private bool displayRawDataField;
        
        private bool displayRawDataFieldSpecified;
        
        private bool displaySensorField;
        
        private bool displaySensorFieldSpecified;
        
        private argDistribType argDistribField;
        
        private bool argDistribFieldSpecified;
        
        private bool displayImageLocationField;
        
        private bool displayImageLocationFieldSpecified;
        
        private bool displayHexIdField;
        
        private bool displayHexIdFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool displayLocation {
            get {
                return this.displayLocationField;
            }
            set {
                this.displayLocationField = value;
                this.RaisePropertyChanged("displayLocation");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool displayLocationSpecified {
            get {
                return this.displayLocationFieldSpecified;
            }
            set {
                this.displayLocationFieldSpecified = value;
                this.RaisePropertyChanged("displayLocationSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public bool displayDiagnostic {
            get {
                return this.displayDiagnosticField;
            }
            set {
                this.displayDiagnosticField = value;
                this.RaisePropertyChanged("displayDiagnostic");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool displayDiagnosticSpecified {
            get {
                return this.displayDiagnosticFieldSpecified;
            }
            set {
                this.displayDiagnosticFieldSpecified = value;
                this.RaisePropertyChanged("displayDiagnosticSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public bool displayMessage {
            get {
                return this.displayMessageField;
            }
            set {
                this.displayMessageField = value;
                this.RaisePropertyChanged("displayMessage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool displayMessageSpecified {
            get {
                return this.displayMessageFieldSpecified;
            }
            set {
                this.displayMessageFieldSpecified = value;
                this.RaisePropertyChanged("displayMessageSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public bool displayCollect {
            get {
                return this.displayCollectField;
            }
            set {
                this.displayCollectField = value;
                this.RaisePropertyChanged("displayCollect");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool displayCollectSpecified {
            get {
                return this.displayCollectFieldSpecified;
            }
            set {
                this.displayCollectFieldSpecified = value;
                this.RaisePropertyChanged("displayCollectSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public bool displayRawData {
            get {
                return this.displayRawDataField;
            }
            set {
                this.displayRawDataField = value;
                this.RaisePropertyChanged("displayRawData");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool displayRawDataSpecified {
            get {
                return this.displayRawDataFieldSpecified;
            }
            set {
                this.displayRawDataFieldSpecified = value;
                this.RaisePropertyChanged("displayRawDataSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public bool displaySensor {
            get {
                return this.displaySensorField;
            }
            set {
                this.displaySensorField = value;
                this.RaisePropertyChanged("displaySensor");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool displaySensorSpecified {
            get {
                return this.displaySensorFieldSpecified;
            }
            set {
                this.displaySensorFieldSpecified = value;
                this.RaisePropertyChanged("displaySensorSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public argDistribType argDistrib {
            get {
                return this.argDistribField;
            }
            set {
                this.argDistribField = value;
                this.RaisePropertyChanged("argDistrib");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool argDistribSpecified {
            get {
                return this.argDistribFieldSpecified;
            }
            set {
                this.argDistribFieldSpecified = value;
                this.RaisePropertyChanged("argDistribSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public bool displayImageLocation {
            get {
                return this.displayImageLocationField;
            }
            set {
                this.displayImageLocationField = value;
                this.RaisePropertyChanged("displayImageLocation");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool displayImageLocationSpecified {
            get {
                return this.displayImageLocationFieldSpecified;
            }
            set {
                this.displayImageLocationFieldSpecified = value;
                this.RaisePropertyChanged("displayImageLocationSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public bool displayHexId {
            get {
                return this.displayHexIdField;
            }
            set {
                this.displayHexIdField = value;
                this.RaisePropertyChanged("displayHexId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool displayHexIdSpecified {
            get {
                return this.displayHexIdFieldSpecified;
            }
            set {
                this.displayHexIdFieldSpecified = value;
                this.RaisePropertyChanged("displayHexIdSpecified");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.dataxmldistribution.argos.cls.fr/types")]
    public enum argDistribType {
        
        /// <remarks/>
        A,
        
        /// <remarks/>
        O,
        
        /// <remarks/>
        B,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.dataxmldistribution.argos.cls.fr/types")]
    public partial class csvRequestType : xmlRequestType {
        
        private bool showHeaderField;
        
        private bool showHeaderFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool showHeader {
            get {
                return this.showHeaderField;
            }
            set {
                this.showHeaderField = value;
                this.RaisePropertyChanged("showHeader");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool showHeaderSpecified {
            get {
                return this.showHeaderFieldSpecified;
            }
            set {
                this.showHeaderFieldSpecified = value;
                this.RaisePropertyChanged("showHeaderSpecified");
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://service.dataxmldistribution.argos.cls.fr/", ConfigurationName="ArgosService.DixServicePortType")]
    public interface DixServicePortType {
        
        // CODEGEN: Generating message contract since the operation getCsv is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="Get Argos data on CSV format", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Wmis.ArgosService.DixException), Action="Get Argos data on CSV format", Name="DixException", Namespace="http://service.dataxmldistribution.argos.cls.fr/types")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(baseRequestType))]
        Wmis.ArgosService.getCsvResponse getCsv(Wmis.ArgosService.getCsvRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="Get Argos data on CSV format", ReplyAction="*")]
        System.Threading.Tasks.Task<Wmis.ArgosService.getCsvResponse> getCsvAsync(Wmis.ArgosService.getCsvRequest request);
        
        // CODEGEN: Generating message contract since the operation getStreamXml is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Wmis.ArgosService.DixException), Action="", Name="DixException", Namespace="http://service.dataxmldistribution.argos.cls.fr/types")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(baseRequestType))]
        Wmis.ArgosService.getStreamXmlResponse getStreamXml(Wmis.ArgosService.getStreamXmlRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Wmis.ArgosService.getStreamXmlResponse> getStreamXmlAsync(Wmis.ArgosService.getStreamXmlRequest request);
        
        // CODEGEN: Generating message contract since the operation getKml is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="Get Argos data on KML format", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Wmis.ArgosService.DixException), Action="Get Argos data on KML format", Name="DixException", Namespace="http://service.dataxmldistribution.argos.cls.fr/types")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(baseRequestType))]
        Wmis.ArgosService.getKmlResponse getKml(Wmis.ArgosService.getKmlRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="Get Argos data on KML format", ReplyAction="*")]
        System.Threading.Tasks.Task<Wmis.ArgosService.getKmlResponse> getKmlAsync(Wmis.ArgosService.getKmlRequest request);
        
        // CODEGEN: Generating message contract since the operation getXml is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="Get Argos data on XML format", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Wmis.ArgosService.DixException), Action="Get Argos data on XML format", Name="DixException", Namespace="http://service.dataxmldistribution.argos.cls.fr/types")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(baseRequestType))]
        Wmis.ArgosService.getXmlResponse getXml(Wmis.ArgosService.getXmlRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="Get Argos data on XML format", ReplyAction="*")]
        System.Threading.Tasks.Task<Wmis.ArgosService.getXmlResponse> getXmlAsync(Wmis.ArgosService.getXmlRequest request);
        
        // CODEGEN: Generating message contract since the operation getXsd is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="Get the XSD for the XML format", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Wmis.ArgosService.DixException), Action="Get the XSD for the XML format", Name="DixException", Namespace="http://service.dataxmldistribution.argos.cls.fr/types")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(baseRequestType))]
        Wmis.ArgosService.getXsdResponse getXsd(Wmis.ArgosService.getXsdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="Get the XSD for the XML format", ReplyAction="*")]
        System.Threading.Tasks.Task<Wmis.ArgosService.getXsdResponse> getXsdAsync(Wmis.ArgosService.getXsdRequest request);
        
        // CODEGEN: Generating message contract since the operation getPlatformList is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="Get the list of platforms", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Wmis.ArgosService.DixException), Action="Get the list of platforms", Name="DixException", Namespace="http://service.dataxmldistribution.argos.cls.fr/types")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(baseRequestType))]
        Wmis.ArgosService.getPlatformListResponse getPlatformList(Wmis.ArgosService.getPlatformListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="Get the list of platforms", ReplyAction="*")]
        System.Threading.Tasks.Task<Wmis.ArgosService.getPlatformListResponse> getPlatformListAsync(Wmis.ArgosService.getPlatformListRequest request);
        
        // CODEGEN: Generating message contract since the operation getObsCsv is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="Get the observations on CSV Format", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Wmis.ArgosService.DixException), Action="Get the observations on CSV Format", Name="DixException", Namespace="http://service.dataxmldistribution.argos.cls.fr/types")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(baseRequestType))]
        Wmis.ArgosService.getObsCsvResponse getObsCsv(Wmis.ArgosService.getObsCsvRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="Get the observations on CSV Format", ReplyAction="*")]
        System.Threading.Tasks.Task<Wmis.ArgosService.getObsCsvResponse> getObsCsvAsync(Wmis.ArgosService.getObsCsvRequest request);
        
        // CODEGEN: Generating message contract since the operation getObsXml is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="Get the observations on XML Format", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Wmis.ArgosService.DixException), Action="Get the observations on XML Format", Name="DixException", Namespace="http://service.dataxmldistribution.argos.cls.fr/types")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(baseRequestType))]
        Wmis.ArgosService.getObsCsvResponse getObsXml(Wmis.ArgosService.getObsCsvRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="Get the observations on XML Format", ReplyAction="*")]
        System.Threading.Tasks.Task<Wmis.ArgosService.getObsCsvResponse> getObsXmlAsync(Wmis.ArgosService.getObsCsvRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getCsvRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.dataxmldistribution.argos.cls.fr/types", Order=0)]
        public Wmis.ArgosService.csvRequestType csvRequest;
        
        public getCsvRequest() {
        }
        
        public getCsvRequest(Wmis.ArgosService.csvRequestType csvRequest) {
            this.csvRequest = csvRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getCsvResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.dataxmldistribution.argos.cls.fr/types", Order=0)]
        public Wmis.ArgosService.stringResponseType csvResponse;
        
        public getCsvResponse() {
        }
        
        public getCsvResponse(Wmis.ArgosService.stringResponseType csvResponse) {
            this.csvResponse = csvResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.dataxmldistribution.argos.cls.fr/types")]
    public partial class streamResponseType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private byte[] returnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=0)]
        public byte[] @return {
            get {
                return this.returnField;
            }
            set {
                this.returnField = value;
                this.RaisePropertyChanged("return");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getStreamXmlRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.dataxmldistribution.argos.cls.fr/types", Order=0)]
        public Wmis.ArgosService.xmlRequestType streamXmlRequest;
        
        public getStreamXmlRequest() {
        }
        
        public getStreamXmlRequest(Wmis.ArgosService.xmlRequestType streamXmlRequest) {
            this.streamXmlRequest = streamXmlRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getStreamXmlResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.dataxmldistribution.argos.cls.fr/types", Order=0)]
        public Wmis.ArgosService.streamResponseType streamXmlResponse;
        
        public getStreamXmlResponse() {
        }
        
        public getStreamXmlResponse(Wmis.ArgosService.streamResponseType streamXmlResponse) {
            this.streamXmlResponse = streamXmlResponse;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getKmlRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.dataxmldistribution.argos.cls.fr/types", Order=0)]
        public Wmis.ArgosService.kmlRequestType kmlRequest;
        
        public getKmlRequest() {
        }
        
        public getKmlRequest(Wmis.ArgosService.kmlRequestType kmlRequest) {
            this.kmlRequest = kmlRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getKmlResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.dataxmldistribution.argos.cls.fr/types", Order=0)]
        public Wmis.ArgosService.stringResponseType kmlResponse;
        
        public getKmlResponse() {
        }
        
        public getKmlResponse(Wmis.ArgosService.stringResponseType kmlResponse) {
            this.kmlResponse = kmlResponse;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getXmlRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.dataxmldistribution.argos.cls.fr/types", Order=0)]
        public Wmis.ArgosService.xmlRequestType xmlRequest;
        
        public getXmlRequest() {
        }
        
        public getXmlRequest(Wmis.ArgosService.xmlRequestType xmlRequest) {
            this.xmlRequest = xmlRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getXmlResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.dataxmldistribution.argos.cls.fr/types", Order=0)]
        public Wmis.ArgosService.stringResponseType xmlResponse;
        
        public getXmlResponse() {
        }
        
        public getXmlResponse(Wmis.ArgosService.stringResponseType xmlResponse) {
            this.xmlResponse = xmlResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.dataxmldistribution.argos.cls.fr/types")]
    public partial class xsdRequestType : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getXsdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.dataxmldistribution.argos.cls.fr/types", Order=0)]
        public Wmis.ArgosService.xsdRequestType xsdRequest;
        
        public getXsdRequest() {
        }
        
        public getXsdRequest(Wmis.ArgosService.xsdRequestType xsdRequest) {
            this.xsdRequest = xsdRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getXsdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.dataxmldistribution.argos.cls.fr/types", Order=0)]
        public Wmis.ArgosService.stringResponseType xsdResponse;
        
        public getXsdResponse() {
        }
        
        public getXsdResponse(Wmis.ArgosService.stringResponseType xsdResponse) {
            this.xsdResponse = xsdResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.dataxmldistribution.argos.cls.fr/types")]
    public partial class platformListRequestType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string usernameField;
        
        private string passwordField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
                this.RaisePropertyChanged("username");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("password");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getPlatformListRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.dataxmldistribution.argos.cls.fr/types", Order=0)]
        public Wmis.ArgosService.platformListRequestType platformListRequest;
        
        public getPlatformListRequest() {
        }
        
        public getPlatformListRequest(Wmis.ArgosService.platformListRequestType platformListRequest) {
            this.platformListRequest = platformListRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getPlatformListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.dataxmldistribution.argos.cls.fr/types", Order=0)]
        public Wmis.ArgosService.stringResponseType platformListResponse;
        
        public getPlatformListResponse() {
        }
        
        public getPlatformListResponse(Wmis.ArgosService.stringResponseType platformListResponse) {
            this.platformListResponse = platformListResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.dataxmldistribution.argos.cls.fr/types")]
    public partial class observationRequestType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string usernameField;
        
        private string passwordField;
        
        private string itemField;
        
        private ItemChoiceType1 itemElementNameField;
        
        private int nbMaxObsField;
        
        private bool nbMaxObsFieldSpecified;
        
        private object item1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
                this.RaisePropertyChanged("username");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("platformId", typeof(string), Order=2)]
        [System.Xml.Serialization.XmlElementAttribute("programNumber", typeof(string), Order=2)]
        [System.Xml.Serialization.XmlElementAttribute("wmo", typeof(string), Order=2)]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
        public string Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
                this.RaisePropertyChanged("Item");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemChoiceType1 ItemElementName {
            get {
                return this.itemElementNameField;
            }
            set {
                this.itemElementNameField = value;
                this.RaisePropertyChanged("ItemElementName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int nbMaxObs {
            get {
                return this.nbMaxObsField;
            }
            set {
                this.nbMaxObsField = value;
                this.RaisePropertyChanged("nbMaxObs");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool nbMaxObsSpecified {
            get {
                return this.nbMaxObsFieldSpecified;
            }
            set {
                this.nbMaxObsFieldSpecified = value;
                this.RaisePropertyChanged("nbMaxObsSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("nbDaysFromNow", typeof(int), Order=5)]
        [System.Xml.Serialization.XmlElementAttribute("period", typeof(periodType), Order=5)]
        public object Item1 {
            get {
                return this.item1Field;
            }
            set {
                this.item1Field = value;
                this.RaisePropertyChanged("Item1");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.dataxmldistribution.argos.cls.fr/types", IncludeInSchema=false)]
    public enum ItemChoiceType1 {
        
        /// <remarks/>
        platformId,
        
        /// <remarks/>
        programNumber,
        
        /// <remarks/>
        wmo,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getObsCsvRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.dataxmldistribution.argos.cls.fr/types", Order=0)]
        public Wmis.ArgosService.observationRequestType observationRequest;
        
        public getObsCsvRequest() {
        }
        
        public getObsCsvRequest(Wmis.ArgosService.observationRequestType observationRequest) {
            this.observationRequest = observationRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getObsCsvResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.dataxmldistribution.argos.cls.fr/types", Order=0)]
        public Wmis.ArgosService.stringResponseType observationResponse;
        
        public getObsCsvResponse() {
        }
        
        public getObsCsvResponse(Wmis.ArgosService.stringResponseType observationResponse) {
            this.observationResponse = observationResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface DixServicePortTypeChannel : Wmis.ArgosService.DixServicePortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DixServicePortTypeClient : System.ServiceModel.ClientBase<Wmis.ArgosService.DixServicePortType>, Wmis.ArgosService.DixServicePortType {
        
        public DixServicePortTypeClient() {
        }
        
        public DixServicePortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DixServicePortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DixServicePortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DixServicePortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Wmis.ArgosService.getCsvResponse Wmis.ArgosService.DixServicePortType.getCsv(Wmis.ArgosService.getCsvRequest request) {
            return base.Channel.getCsv(request);
        }
        
        public Wmis.ArgosService.stringResponseType getCsv(Wmis.ArgosService.csvRequestType csvRequest) {
            Wmis.ArgosService.getCsvRequest inValue = new Wmis.ArgosService.getCsvRequest();
            inValue.csvRequest = csvRequest;
            Wmis.ArgosService.getCsvResponse retVal = ((Wmis.ArgosService.DixServicePortType)(this)).getCsv(inValue);
            return retVal.csvResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Wmis.ArgosService.getCsvResponse> Wmis.ArgosService.DixServicePortType.getCsvAsync(Wmis.ArgosService.getCsvRequest request) {
            return base.Channel.getCsvAsync(request);
        }
        
        public System.Threading.Tasks.Task<Wmis.ArgosService.getCsvResponse> getCsvAsync(Wmis.ArgosService.csvRequestType csvRequest) {
            Wmis.ArgosService.getCsvRequest inValue = new Wmis.ArgosService.getCsvRequest();
            inValue.csvRequest = csvRequest;
            return ((Wmis.ArgosService.DixServicePortType)(this)).getCsvAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Wmis.ArgosService.getStreamXmlResponse Wmis.ArgosService.DixServicePortType.getStreamXml(Wmis.ArgosService.getStreamXmlRequest request) {
            return base.Channel.getStreamXml(request);
        }
        
        public Wmis.ArgosService.streamResponseType getStreamXml(Wmis.ArgosService.xmlRequestType streamXmlRequest) {
            Wmis.ArgosService.getStreamXmlRequest inValue = new Wmis.ArgosService.getStreamXmlRequest();
            inValue.streamXmlRequest = streamXmlRequest;
            Wmis.ArgosService.getStreamXmlResponse retVal = ((Wmis.ArgosService.DixServicePortType)(this)).getStreamXml(inValue);
            return retVal.streamXmlResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Wmis.ArgosService.getStreamXmlResponse> Wmis.ArgosService.DixServicePortType.getStreamXmlAsync(Wmis.ArgosService.getStreamXmlRequest request) {
            return base.Channel.getStreamXmlAsync(request);
        }
        
        public System.Threading.Tasks.Task<Wmis.ArgosService.getStreamXmlResponse> getStreamXmlAsync(Wmis.ArgosService.xmlRequestType streamXmlRequest) {
            Wmis.ArgosService.getStreamXmlRequest inValue = new Wmis.ArgosService.getStreamXmlRequest();
            inValue.streamXmlRequest = streamXmlRequest;
            return ((Wmis.ArgosService.DixServicePortType)(this)).getStreamXmlAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Wmis.ArgosService.getKmlResponse Wmis.ArgosService.DixServicePortType.getKml(Wmis.ArgosService.getKmlRequest request) {
            return base.Channel.getKml(request);
        }
        
        public Wmis.ArgosService.stringResponseType getKml(Wmis.ArgosService.kmlRequestType kmlRequest) {
            Wmis.ArgosService.getKmlRequest inValue = new Wmis.ArgosService.getKmlRequest();
            inValue.kmlRequest = kmlRequest;
            Wmis.ArgosService.getKmlResponse retVal = ((Wmis.ArgosService.DixServicePortType)(this)).getKml(inValue);
            return retVal.kmlResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Wmis.ArgosService.getKmlResponse> Wmis.ArgosService.DixServicePortType.getKmlAsync(Wmis.ArgosService.getKmlRequest request) {
            return base.Channel.getKmlAsync(request);
        }
        
        public System.Threading.Tasks.Task<Wmis.ArgosService.getKmlResponse> getKmlAsync(Wmis.ArgosService.kmlRequestType kmlRequest) {
            Wmis.ArgosService.getKmlRequest inValue = new Wmis.ArgosService.getKmlRequest();
            inValue.kmlRequest = kmlRequest;
            return ((Wmis.ArgosService.DixServicePortType)(this)).getKmlAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Wmis.ArgosService.getXmlResponse Wmis.ArgosService.DixServicePortType.getXml(Wmis.ArgosService.getXmlRequest request) {
            return base.Channel.getXml(request);
        }
        
        public Wmis.ArgosService.stringResponseType getXml(Wmis.ArgosService.xmlRequestType xmlRequest) {
            Wmis.ArgosService.getXmlRequest inValue = new Wmis.ArgosService.getXmlRequest();
            inValue.xmlRequest = xmlRequest;
            Wmis.ArgosService.getXmlResponse retVal = ((Wmis.ArgosService.DixServicePortType)(this)).getXml(inValue);
            return retVal.xmlResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Wmis.ArgosService.getXmlResponse> Wmis.ArgosService.DixServicePortType.getXmlAsync(Wmis.ArgosService.getXmlRequest request) {
            return base.Channel.getXmlAsync(request);
        }
        
        public System.Threading.Tasks.Task<Wmis.ArgosService.getXmlResponse> getXmlAsync(Wmis.ArgosService.xmlRequestType xmlRequest) {
            Wmis.ArgosService.getXmlRequest inValue = new Wmis.ArgosService.getXmlRequest();
            inValue.xmlRequest = xmlRequest;
            return ((Wmis.ArgosService.DixServicePortType)(this)).getXmlAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Wmis.ArgosService.getXsdResponse Wmis.ArgosService.DixServicePortType.getXsd(Wmis.ArgosService.getXsdRequest request) {
            return base.Channel.getXsd(request);
        }
        
        public Wmis.ArgosService.stringResponseType getXsd(Wmis.ArgosService.xsdRequestType xsdRequest) {
            Wmis.ArgosService.getXsdRequest inValue = new Wmis.ArgosService.getXsdRequest();
            inValue.xsdRequest = xsdRequest;
            Wmis.ArgosService.getXsdResponse retVal = ((Wmis.ArgosService.DixServicePortType)(this)).getXsd(inValue);
            return retVal.xsdResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Wmis.ArgosService.getXsdResponse> Wmis.ArgosService.DixServicePortType.getXsdAsync(Wmis.ArgosService.getXsdRequest request) {
            return base.Channel.getXsdAsync(request);
        }
        
        public System.Threading.Tasks.Task<Wmis.ArgosService.getXsdResponse> getXsdAsync(Wmis.ArgosService.xsdRequestType xsdRequest) {
            Wmis.ArgosService.getXsdRequest inValue = new Wmis.ArgosService.getXsdRequest();
            inValue.xsdRequest = xsdRequest;
            return ((Wmis.ArgosService.DixServicePortType)(this)).getXsdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Wmis.ArgosService.getPlatformListResponse Wmis.ArgosService.DixServicePortType.getPlatformList(Wmis.ArgosService.getPlatformListRequest request) {
            return base.Channel.getPlatformList(request);
        }
        
        public Wmis.ArgosService.stringResponseType getPlatformList(Wmis.ArgosService.platformListRequestType platformListRequest) {
            Wmis.ArgosService.getPlatformListRequest inValue = new Wmis.ArgosService.getPlatformListRequest();
            inValue.platformListRequest = platformListRequest;
            Wmis.ArgosService.getPlatformListResponse retVal = ((Wmis.ArgosService.DixServicePortType)(this)).getPlatformList(inValue);
            return retVal.platformListResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Wmis.ArgosService.getPlatformListResponse> Wmis.ArgosService.DixServicePortType.getPlatformListAsync(Wmis.ArgosService.getPlatformListRequest request) {
            return base.Channel.getPlatformListAsync(request);
        }
        
        public System.Threading.Tasks.Task<Wmis.ArgosService.getPlatformListResponse> getPlatformListAsync(Wmis.ArgosService.platformListRequestType platformListRequest) {
            Wmis.ArgosService.getPlatformListRequest inValue = new Wmis.ArgosService.getPlatformListRequest();
            inValue.platformListRequest = platformListRequest;
            return ((Wmis.ArgosService.DixServicePortType)(this)).getPlatformListAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Wmis.ArgosService.getObsCsvResponse Wmis.ArgosService.DixServicePortType.getObsCsv(Wmis.ArgosService.getObsCsvRequest request) {
            return base.Channel.getObsCsv(request);
        }
        
        public Wmis.ArgosService.stringResponseType getObsCsv(Wmis.ArgosService.observationRequestType observationRequest) {
            Wmis.ArgosService.getObsCsvRequest inValue = new Wmis.ArgosService.getObsCsvRequest();
            inValue.observationRequest = observationRequest;
            Wmis.ArgosService.getObsCsvResponse retVal = ((Wmis.ArgosService.DixServicePortType)(this)).getObsCsv(inValue);
            return retVal.observationResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Wmis.ArgosService.getObsCsvResponse> Wmis.ArgosService.DixServicePortType.getObsCsvAsync(Wmis.ArgosService.getObsCsvRequest request) {
            return base.Channel.getObsCsvAsync(request);
        }
        
        public System.Threading.Tasks.Task<Wmis.ArgosService.getObsCsvResponse> getObsCsvAsync(Wmis.ArgosService.observationRequestType observationRequest) {
            Wmis.ArgosService.getObsCsvRequest inValue = new Wmis.ArgosService.getObsCsvRequest();
            inValue.observationRequest = observationRequest;
            return ((Wmis.ArgosService.DixServicePortType)(this)).getObsCsvAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Wmis.ArgosService.getObsCsvResponse Wmis.ArgosService.DixServicePortType.getObsXml(Wmis.ArgosService.getObsCsvRequest request) {
            return base.Channel.getObsXml(request);
        }
        
        public Wmis.ArgosService.stringResponseType getObsXml(Wmis.ArgosService.observationRequestType observationRequest) {
            Wmis.ArgosService.getObsCsvRequest inValue = new Wmis.ArgosService.getObsCsvRequest();
            inValue.observationRequest = observationRequest;
            Wmis.ArgosService.getObsCsvResponse retVal = ((Wmis.ArgosService.DixServicePortType)(this)).getObsXml(inValue);
            return retVal.observationResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Wmis.ArgosService.getObsCsvResponse> Wmis.ArgosService.DixServicePortType.getObsXmlAsync(Wmis.ArgosService.getObsCsvRequest request) {
            return base.Channel.getObsXmlAsync(request);
        }
        
        public System.Threading.Tasks.Task<Wmis.ArgosService.getObsCsvResponse> getObsXmlAsync(Wmis.ArgosService.observationRequestType observationRequest) {
            Wmis.ArgosService.getObsCsvRequest inValue = new Wmis.ArgosService.getObsCsvRequest();
            inValue.observationRequest = observationRequest;
            return ((Wmis.ArgosService.DixServicePortType)(this)).getObsXmlAsync(inValue);
        }
    }
}
